In [1]:
import sys
sys.path.append('../')
sys.path

['/home/andrecosta/sideprojects/transformer/notebooks',
 '/home/andrecosta/anaconda3/lib/python312.zip',
 '/home/andrecosta/anaconda3/lib/python3.12',
 '/home/andrecosta/anaconda3/lib/python3.12/lib-dynload',
 '',
 '/home/andrecosta/anaconda3/lib/python3.12/site-packages',
 '../']

In [2]:
from transformer.embed import Embeddings
from transformer.penc import PositionalEncoding

import altair as alt
import pandas as pd

import torch
import torch.nn as nn

import copy

%load_ext autoreload
%autoreload 2

In [3]:
d_model = 6
src_vocab = 3

In [4]:
c = copy.deepcopy
position = PositionalEncoding(d_model, dropout=0)
embedding = Embeddings(d_model, src_vocab)
src_embed = nn.Sequential(c(embedding), c(position))
src_embed_wo_pe = c(embedding) # w/o positional encoding

In [5]:
src = torch.LongTensor([[0, 2]])

In [6]:
src_embed(src)

tensor([[[ 3.7370, -2.5465, -0.9624, -0.3924, -2.9096,  6.1531],
         [-0.4408,  0.0682,  2.4366,  1.9158,  2.3523,  1.0171]]],
       grad_fn=<AddBackward0>)

In [7]:
z = src_embed_wo_pe(src)
z

tensor([[[ 3.7370, -3.5465, -0.9624, -1.3924, -2.9096,  5.1531],
         [-1.2823, -0.4721,  2.3902,  0.9169,  2.3502,  0.0171]]],
       grad_fn=<MulBackward0>)

In [8]:
c(position)(z)

tensor([[[ 3.7370, -2.5465, -0.9624, -0.3924, -2.9096,  6.1531],
         [-0.4408,  0.0682,  2.4366,  1.9158,  2.3523,  1.0171]]],
       grad_fn=<AddBackward0>)