In [2]:
import sys
sys.path.append('../')
sys.path

['/home/andrecosta/sideprojects/transformer/notebooks',
 '/home/andrecosta/anaconda3/lib/python312.zip',
 '/home/andrecosta/anaconda3/lib/python3.12',
 '/home/andrecosta/anaconda3/lib/python3.12/lib-dynload',
 '',
 '/home/andrecosta/anaconda3/lib/python3.12/site-packages',
 '../']

In [9]:
from transformer.embed import Embeddings
from transformer.penc import PositionalEncoding

import altair as alt
import pandas as pd

import torch
import torch.nn as nn

import copy

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [117]:
d_model = 6
src_vocab = 3

In [118]:
c = copy.deepcopy
position = PositionalEncoding(d_model, dropout=0)
embedding = Embeddings(d_model, src_vocab)
src_embed = nn.Sequential(c(embedding), c(position))
src_embed_wo_pe = c(embedding) # w/o positional encoding

In [125]:
src = torch.LongTensor([[0, 2]])

In [127]:
src_embed(src)

tensor([[[ 2.1633,  0.2062,  0.5971,  1.9703,  0.3285,  4.7211],
         [ 2.8611, -3.2178, -1.3646,  2.2150, -2.2005,  3.5237]]],
       grad_fn=<AddBackward0>)

In [128]:
z = src_embed_wo_pe(src)
z

tensor([[[ 2.1633, -0.7938,  0.5971,  0.9703,  0.3285,  3.7211],
         [ 2.0196, -3.7581, -1.4110,  1.2161, -2.2027,  2.5237]]],
       grad_fn=<MulBackward0>)

In [133]:
c(position)(z)

tensor([[[ 2.1633,  0.2062,  0.5971,  1.9703,  0.3285,  4.7211],
         [ 2.8611, -3.2178, -1.3646,  2.2150, -2.2005,  3.5237]]],
       grad_fn=<AddBackward0>)